name       : python-parted
version    : 3.10.7
release    : 7
source     :
    - https://pypi.python.org/packages/2c/a9/69f67f6d5d2fd80ef3d60dc5bef4971d837dc741be0d53295d3aabb5ec7f/pyparted-3.10.7.tar.gz : 78cbea4359782deb95efc074444909686952fcbfc19b97e15c06ca7dbfed8d2c
license    : GPL-2.0
component  : programming.python
summary    : Python bindings to libparted
description: |
    Python bindings to libparted.
builddeps  :
    - pkgconfig(libparted)
    - pkgconfig(python3)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
